common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "natural"
  partition_method: "natural"
  feature_col: user_id

model_args:
  model: "har_cnn"

train_args:
  federated_optimizer: "Custom" #should not matter
  client_id_list: "[]"  # Adjust based on num_clients
  client_num_in_total: 100 # ignored
  client_num_per_round: 10
  comm_round: 200
  learning_rate: 0.01
  weight_decay: 0
  epochs: 5
  batch_size: -1
  client_optimizer: "sgd"
  n_basis: 5
  preference: -0.1
  


validation_args:
  frequency_of_the_test: 10
  test_only_users: 0

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_wandb: true
  wandb_entity: s-urso2
  wandb_project: "FedHAR"
  run_name: "run_cluster_har"

