program: my_fedml_script.py
method: grid  # or 'grid', 'random'
metric:
  name: Server/Test/Acc  # FedML typically logs as 'test/acc' or 'test_acc'
  goal: maximize

parameters:
  train_args:
    parameters:
      learning_rate:
        
        values : [0.1,0.01,0.001]
      
      weight_decay:
        values : [0.0001,0.00001,0]
      
      batch_size:
        values: [-1]
      
      client_num_per_round:
        values: [10]
      
      epochs:
        values: [5]


command:
  - uv
  - run
  - ${program}
  - --cf
  - my_fedml_config_1.yaml