common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "cifar10"
  partition_method: "label" 
  method_name: "dirichlet"
  validation_split: 0.1 # only used by cluster_prune_script
  
  
model_args:
  model: "resnet18"

train_args:
  federated_optimizer: "SCAFFOLD" 
  client_id_list: "[]" 
  client_num_in_total: 100 
  client_num_per_round: 10
  comm_round: 500
  learning_rate: 0.1
  weight_decay: 0.0001
  epochs: 5
  batch_size: -1
  client_optimizer: "sgd"
# cluster params
  n_basis: 5
  preference: median # -90, -60, 
  group_method: clusters
#pruning params
  pruning: "proposal" # "random"
  ssl_coefficient: 0
  prune_percent: 0.1
  accuracy_threshold: 0.3
  consolidation_percentage: 0.1
  consensus_percentage: 0.5
# cifar config
  initialize_all_clients: False
  server_lr: 0.1


validation_args:
  frequency_of_the_test: 10
  # test_only_users: 0

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  enable_wandb: true
  wandb_entity: s-urso2
  wandb_project: "Tests"
  run_name: "run_fedavg_cifar"