program: scripts/my_fedml_script.py 
method: grid  # or 'grid', 'random'
metric:
  name: Server/Test/Acc  # FedML typically logs as 'test/acc' or 'test_acc'
  goal: maximize

parameters:
  train_args:
    parameters:
      learning_rate: 
        values : [0.1]

  device_args:
    parameters:
      gpu_id: 
        values: [1]
      
command:
  - uv
  - run
  - --env-file
  - .env
  - --
  - ${program}
  - --cf
  - configs/femnist_config.yaml